// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMlyVMFeQ6SAn-8NQIhGAKLCmui0al03M',
    appId: '1:809573891168:web:36c4eaf3462daf745b5705',
    messagingSenderId: '809573891168',
    projectId: 'panafix-app',
    authDomain: 'panafix-app.firebaseapp.com',
    storageBucket: 'panafix-app.firebasestorage.app',
    measurementId: 'G-YG2QC843SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbqx6py8QC4UqhqVRfLQiIleTq4DtD2Es',
    appId: '1:809573891168:android:9633ba3d24e653fc5b5705',
    messagingSenderId: '809573891168',
    projectId: 'panafix-app',
    storageBucket: 'panafix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtV1TEaqEzN-qAXSYT2fSOfeWALvWk9rk',
    appId: '1:809573891168:ios:43949c63eb4601545b5705',
    messagingSenderId: '809573891168',
    projectId: 'panafix-app',
    storageBucket: 'panafix-app.firebasestorage.app',
    iosBundleId: 'com.example.panafix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtV1TEaqEzN-qAXSYT2fSOfeWALvWk9rk',
    appId: '1:809573891168:ios:43949c63eb4601545b5705',
    messagingSenderId: '809573891168',
    projectId: 'panafix-app',
    storageBucket: 'panafix-app.firebasestorage.app',
    iosBundleId: 'com.example.panafix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMlyVMFeQ6SAn-8NQIhGAKLCmui0al03M',
    appId: '1:809573891168:web:390b34be0eb700c15b5705',
    messagingSenderId: '809573891168',
    projectId: 'panafix-app',
    authDomain: 'panafix-app.firebaseapp.com',
    storageBucket: 'panafix-app.firebasestorage.app',
    measurementId: 'G-JDF65FHM5Y',
  );
}